version: '3.8'

services:
  web:
    build: .
    command: gunicorn trackify.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build:
      context: ./ngnix
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/staticfiles

volumes:
  postgres_data:
  static_volume: